services:
  nginx:
    image: nginx:1.27-alpine
    container_name: devops-proxy
    ports:
      - "${PROXY_HTTP_PORT:-8081}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
    networks:
      - devops-edge
    restart: unless-stopped

networks:
  devops-edge:
    external: true